### ISSUE TITLE
Keep uppercase option

### ISSUE THREAD

**Issue by ramon-nogueira** [edDimensi/html2pug#8]
Hello.. I love https://html2pug.now.sh/

I used to develop Angular Apps and it's case sensitive.
Can we have an option to keep uppercase letters in code? The PUG is always being in lowercase mode.
Thanks!

**Comment by dimensi** [comment]
Plz give a example. What do you expect?

**Comment by ramon-nogueira** [comment]
For example:

```
<nz-page-header class="site-page-header" (nzBack)="onBack()" nzBackIcon nzTitle="Title" nzSubtitle="This is a subtitle">
</nz-page-header>
```

is transformed to:

```
nz-page-header.site-page-header((nzback)="onBack()", nzbackicon="", nztitle="Title", nzsubtitle="This is a subtitle")
```

I expect

```
nz-page-header.site-page-header((nzback)="onBack()", nzBackIcon="", nzTitle="Title", nzSubtitle="This is a subtitle")
```

**Comment by dimensi** [comment]
Well I think I could resolve this issue. I'll rewrite compiler from ground.
 
![image](https://user-images.githubusercontent.com/11390039/106203695-dd5cc800-61cc-11eb-89c5-ab69d27cb825.png)

I've already get some results.

**Comment by dimensi** [comment]
You can check results here https://github.com/dimensi/html2pug/pull/9

**Comment by dimensi** [comment]
I've merged branch, now you @ramon-nogueira can look here https://html2pug.now.sh/

**Comment by altShiftDev** [comment]
I just tested this and the bug is still present, here's a test case:

`<MyCustomComponent/>` becomes => `mycustomcomponent`

Because components are case sensitive in angular/vue/react `mycustomcomponent` throws errors as `undefined`.

**Comment by dimensi** [comment]
Added support for these kinds of templates with @vue/compiler-dom. Give it a try.


![image](https://user-images.githubusercontent.com/11390039/147862398-b541f893-14b9-4b89-b45f-4582fba08253.png)

**Comment by altShiftDev** [comment]
The new layout looks nice but the bug is still present:

`<MyCustomComponent/>` becomes `mycustomcomponent` all lowercase.

**Comment by dimensi** [comment]
![image](https://user-images.githubusercontent.com/11390039/147863384-1938279a-244f-460e-b730-dc0660d38a74.png)

result:
```pug
QBtn(icon="event" round color="primary")
  QPopupProxy(@before-show="updateProxy" cover transition-show="scale" transition-hide="scale")
    QDate(v-model="proxyDate")
      .row.items-center.justify-end.q-gutter-sm
        QBtn(label="Cancel" color="primary" flat v-close-popup)
        QBtn(label="OK" color="primary" flat @click="save" v-close-popup)
```

**Comment by dimensi** [comment]
No response from the author. I added the function and checked it myself. I am closing this issue. If there are any comments, you can reopen it.
